// ─────────────────────────────────────────────────────────────────────────────
// data.js — Tranches and customers for all four platforms
//
// HOW TO ADD A CUSTOMER:
//   1. Find the right platform section below
//   2. Copy an existing entry and paste at the end of that section
//   3. Update: _id (must be unique), t (tranche id), name, cid, freq, st,
//      hd, csm, notes, job, lnk
//   4. Save and commit to GitHub
// ─────────────────────────────────────────────────────────────────────────────

// Date helper — days from base date
const BASE_DATE = new Date('2026-04-02');
function add(days) {
  const d = new Date(BASE_DATE);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

const TRANCHES = [

  // ── NGPI ──
  { _id:'t0',  Title:'Tranche 0',  Platform:'ngpi', Phase:'Matching',  Customers:12, CSM:'Sarah K.',  GoLive:add(45),  Notes:null },
  { _id:'t1',  Title:'Tranche 1',  Platform:'ngpi', Phase:'Matching',  Customers:7,  CSM:'James T.',  GoLive:add(50),  Notes:null },
  { _id:'t2',  Title:'Tranche 2',  Platform:'ngpi', Phase:'Matching',  Customers:11, CSM:'Maria L.',  GoLive:add(60),  Notes:null },
  { _id:'t3',  Title:'Tranche 3',  Platform:'ngpi', Phase:'Matching',  Customers:10,  CSM:'David R.',  GoLive:add(65),  Notes:null },
  { _id:'t4',  Title:'Tranche 4',  Platform:'ngpi', Phase:'Matching',  Customers:6,  CSM:'Priya N.',  GoLive:add(70),  Notes:null },
  { _id:'t5',  Title:'Tranche 5',  Platform:'ngpi', Phase:'Discovery', Customers:7,  CSM:'Tom W.',    GoLive:add(90),  Notes:null },
  { _id:'t6',  Title:'Tranche 6',  Platform:'ngpi', Phase:'Matching',  Customers:7,  CSM:'Sarah K.',  GoLive:add(55),  Notes:null },
  { _id:'t7',  Title:'Tranche 7',  Platform:'ngpi', Phase:'Matching',  Customers:1,  CSM:'James T.',  GoLive:add(60),  Notes:null },
  { _id:'t8',  Title:'Tranche 8',  Platform:'ngpi', Phase:'Discovery', Customers:7,  CSM:'Maria L.',  GoLive:add(100), Notes:null },
  { _id:'t9',  Title:'Tranche 9',  Platform:'ngpi', Phase:'Discovery', Customers:7,  CSM:'David R.',  GoLive:add(105), Notes:null },
  { _id:'t10', Title:'Tranche 10', Platform:'ngpi', Phase:'Discovery', Customers:7,  CSM:'Priya N.',  GoLive:add(115), Notes:null },
  { _id:'t11', Title:'Tranche 11', Platform:'ngpi', Phase:'Discovery', Customers:8,  CSM:'Tom W.',    GoLive:add(120), Notes:null },
  { _id:'t12', Title:'Tranche 12', Platform:'ngpi', Phase:'Discovery', Customers:6,  CSM:'Sarah K.',  GoLive:add(150), Notes:'Largest: Radwell and Zoro' },
  { _id:'t13', Title:'Tranche 13', Platform:'ngpi', Phase:'Discovery', Customers:2,  CSM:'James T.',  GoLive:add(160), Notes:'Incoming — not started' },

  // ── BPA ──
  { _id:'bpa-t1', Title:'BPA Active',          Platform:'bpa', Phase:'Discovery', Customers:78, CSM:'Maria L.', GoLive:add(120), Notes:'Tranche assignments TBD' },
  { _id:'bpa-t2', Title:'BPA Churned / Ignored',Platform:'bpa', Phase:'Discovery', Customers:4,  CSM:'Maria L.', GoLive:null,     Notes:'4 customers ignored or churned' },

  // ── WISER MAP ──
  { _id:'wmap-t1', Title:'Wiser MAP', Platform:'wmap', Phase:'Discovery', Customers:14, CSM:'David R.', GoLive:add(110), Notes:null },

  // ── NUMAP (CyberAnalyst) ──
  { _id:'nm-t1', Title:'NuMap Tranche 1', Platform:'numap', Phase:'Discovery', Customers:20, CSM:'Priya N.', GoLive:add(90),  Notes:'20 customers' },
  { _id:'nm-t2', Title:'NuMap Tranche 2', Platform:'numap', Phase:'Discovery', Customers:7,  CSM:'Priya N.', GoLive:add(110), Notes:'7 customers' },
  { _id:'nm-t3', Title:'NuMap Tranche 3', Platform:'numap', Phase:'Discovery', Customers:9,  CSM:'Tom W.',   GoLive:add(130), Notes:'9 customers' },
];

// ─────────────────────────────────────────────────────────────────────────────
// CUSTOMERS
// Fields: _id, t (tranche id), p (platform), name, cid, freq, st (status),
//         hd (handoff date), csm, notes, job (discovery job name), lnk (job link)
// ─────────────────────────────────────────────────────────────────────────────
const CUSTOMERS_RAW = [

  // ── NGPI — Tranche 0 ──
  { _id:'n0', t:'t0', p:'ngpi', name:'Toshiba', cid:'555158', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    customertoshiba (555158) Job Name                         NaN Job Name                         NaN Name: 0, dtype: object', lnk:null },
  { _id:'n1', t:'t0', p:'ngpi', name:'Homehardwarelbm', cid:'555028', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Home Hardware LBM (555028) Job Name                           NaN Job Name                           NaN Name: 1, dtype: object', lnk:null },
  { _id:'n2', t:'t0', p:'ngpi', name:'Pcconnection', cid:'555063', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    PC Connection (555063) Job Name                       NaN Job Name                       NaN Name: 2, dtype: object', lnk:null },
  { _id:'n3', t:'t0', p:'ngpi', name:'Autobarn AU', cid:'555386', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Autobarn AU (555386) Job Name                     NaN Job Name                     NaN Name: 3, dtype: object', lnk:null },
  { _id:'n4', t:'t0', p:'ngpi', name:'Adorama', cid:'555593', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    customeradora maorgid527 (555593) Job Name                                  NaN Job Name                                  NaN Name: 4, dtype: object', lnk:null },
  { _id:'n5', t:'t0', p:'ngpi', name:'DigiDirect', cid:'555718', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    customerdigidirectorgid664 (555718) Job Name                                    NaN Job Name                                    NaN Name: 5, dtype: object', lnk:null },
  { _id:'n6', t:'t0', p:'ngpi', name:'Costcocanada', cid:'555385', freq:'Biweekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    CostcoCA (555385) - Full Discovery Job Name                                   NaN Job Name                                   NaN Name: 6, dtype: object', lnk:null },
  { _id:'n7', t:'t0', p:'ngpi', name:'Bestbuy', cid:'555070', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 7, dtype: object', lnk:null },
  { _id:'n8', t:'t0', p:'ngpi', name:'BBY US Fulfillment 2', cid:'555623', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Bbyfulfill2 (555623) Job Name                     NaN Job Name                     NaN Name: 8, dtype: object', lnk:null },
  { _id:'n9', t:'t0', p:'ngpi', name:'Home Hardware', cid:'555027', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Home Hardware Hardline (555027) Job Name                                NaN Job Name                                NaN Name: 9, dtype: object', lnk:null },
  { _id:'n10', t:'t0', p:'ngpi', name:'Academy Sports', cid:'555639', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Academy Sports (555639) Job Name                        NaN Job Name                        NaN Name: 10, dtype: object', lnk:null },
  { _id:'n11', t:'t0', p:'ngpi', name:'BBY US Fulfillment', cid:'555595', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Bbyfulfill (555595) Job Name                    NaN Job Name                    NaN Name: 11, dtype: object', lnk:null },

  // ── NGPI — Tranche 1 ──
  { _id:'n12', t:'t1', p:'ngpi', name:'Petwise', cid:'555755', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Petwise (555755*) (555755) Job Name                           NaN Job Name                           NaN Name: 0, dtype: object', lnk:null },
  { _id:'n13', t:'t1', p:'ngpi', name:'Rrigoods', cid:'555754', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Rrigoods700 (555754) - Full Discovery Job Name                                      NaN Job Name                                      NaN Name: 1, dtype: object', lnk:null },
  { _id:'n14', t:'t1', p:'ngpi', name:'Officeworks B2B', cid:'555794', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    OfficeworksB2B  - Full Discovery (555794) Job Name                                          NaN Job Name                                          NaN Name: 2, dtype: object', lnk:null },
  { _id:'n15', t:'t1', p:'ngpi', name:'Thebrick', cid:'555328', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    TheBrick (555328) - Full Discovery Job Name                                   NaN Job Name                                   NaN Name: 3, dtype: object', lnk:null },
  { _id:'n16', t:'t1', p:'ngpi', name:'Woolworths 3P', cid:'555786', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Woolworths3  - Full Discovery (555786) Job Name                                       NaN Job Name                                       NaN Name: 4, dtype: object', lnk:null },
  { _id:'n17', t:'t1', p:'ngpi', name:'Repairclinic', cid:'555439', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    RepairClinic  - Full Discovery (555439) Job Name                                        NaN Job Name                                        NaN Name: 5, dtype: object', lnk:null },
  { _id:'n18', t:'t1', p:'ngpi', name:'Parts Express', cid:'555787', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    PartsExpress  - Full Discovery (555787) Job Name                                        NaN Job Name                                        NaN Name: 6, dtype: object', lnk:null },

  // ── NGPI — Tranche 2 ──
  { _id:'n19', t:'t2', p:'ngpi', name:'Electrolux', cid:'555834', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Electrolux780 (555834) - Full Discovery Job Name                                        NaN Job Name                                        NaN Name: 0, dtype: object', lnk:null },
  { _id:'n20', t:'t2', p:'ngpi', name:'Electroluxcdiscount', cid:'555835', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Electroluxcdiscount781 (555835) - Full Discovery Job Name                                                 NaN Job Name                                                 NaN Name: 1, dtype: object', lnk:null },
  { _id:'n21', t:'t2', p:'ngpi', name:'Rockler', cid:'555747', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Rockler693 (555747) - Full Discovery Job Name                                     NaN Job Name                                     NaN Name: 2, dtype: object', lnk:null },
  { _id:'n22', t:'t2', p:'ngpi', name:'Costco Australia Tyres', cid:'555752', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    CostcoAU698 (555752) - Full Discovery Job Name                                      NaN Job Name                                      NaN Name: 3, dtype: object', lnk:null },
  { _id:'n23', t:'t2', p:'ngpi', name:'Rocky Mountain Tusk', cid:'555833', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Rockymountaintusk779  (555833) - Full Discovery Job Name                                                NaN Job Name                                                NaN Name: 4, dtype: object', lnk:null },
  { _id:'n24', t:'t2', p:'ngpi', name:'Lumber', cid:'555154', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    84lumber (555154) - Full Discovery Job Name                                   NaN Job Name                                   NaN Name: 5, dtype: object', lnk:null },
  { _id:'n25', t:'t2', p:'ngpi', name:'Shell', cid:'555653', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Shell  - Full Discovery (555653) Job Name                                 NaN Job Name                                 NaN Name: 6, dtype: object', lnk:null },
  { _id:'n26', t:'t2', p:'ngpi', name:'Sutton Tools', cid:'555234', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    SuttonTools  - Full Discovery (555234) Job Name                                       NaN Job Name                                       NaN Name: 7, dtype: object', lnk:null },
  { _id:'n27', t:'t2', p:'ngpi', name:'J.D. Irving', cid:'555722', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    JDIrving  - Full Discovery (555722) Job Name                                    NaN Job Name                                    NaN Name: 8, dtype: object', lnk:null },
  { _id:'n28', t:'t2', p:'ngpi', name:'Masco', cid:'555036', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Masco  - Full Discovery3Jan 20, 2026COMPLETE96... Job Name                                                  NaN Job Name                                                  NaN Name: 9, dtype: object', lnk:null },
  { _id:'n29', t:'t2', p:'ngpi', name:'Prime Line', cid:'555788', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    Primeline (555788) - Full Discovery Job Name                                    NaN Job Name                                    NaN Name: 10, dtype: object', lnk:null },

  // ── NGPI — Tranche 3 ──
  { _id:'n30', t:'t3', p:'ngpi', name:'Oscar de France', cid:'555735', freq:null, st:'churned', hd:add(60), csm:'', notes:'customer churned', job:'1 Job Name    Disabled Job Name         NaN Job Name         NaN Name: 0, dtype: object', lnk:null },
  { _id:'n31', t:'t3', p:'ngpi', name:'All Promos', cid:'555770', freq:null, st:'production', hd:add(60), csm:'', notes:'complete', job:'1 Job Name    4allpromosorgid716 555770 - Full Discovery v-gk Job Name                                                NaN Job Name                                                NaN Name: 1, dtype: object', lnk:null },
  { _id:'n32', t:'t3', p:'ngpi', name:'Purinacanada', cid:'555641', freq:null, st:'production', hd:add(60), csm:'', notes:'checking, Found BOT issues', job:'1 Job Name    purinacanadaorgid574 555641 - Full Discovery v-iv Job Name                                                  NaN Job Name                                                  NaN Name: 2, dtype: object', lnk:null },
  { _id:'n33', t:'t3', p:'ngpi', name:'Harvey Norman Bathrooms', cid:'555778', freq:null, st:'production', hd:add(60), csm:'', notes:'checking', job:'1 Job Name    harveynormanbathroomsorgid724 555778 - Full Di... Job Name                                                  NaN Job Name                                                  NaN Name: 3, dtype: object', lnk:null },
  { _id:'n34', t:'t3', p:'ngpi', name:'Costco Australia', cid:'555756', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    costcoaustraliad16d93orgid702 555756 - Full Di... Job Name                                                  NaN Job Name                                                  NaN Name: 4, dtype: object', lnk:null },
  { _id:'n35', t:'t3', p:'ngpi', name:'Ellsworth', cid:'555749', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    ellsworthorgid695 555749 - Full Discovery v-dz Job Name                                               NaN Job Name                                               NaN Name: 5, dtype: object', lnk:null },
  { _id:'n36', t:'t3', p:'ngpi', name:'Henry Schein', cid:'555799', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    henrysheinorgid745 555799 - Full Discovery v-4k Job Name                                                NaN Job Name                                                NaN Name: 6, dtype: object', lnk:null },
  { _id:'n37', t:'t3', p:'ngpi', name:'The Pet Place', cid:'555844', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    thepetplaceorgid790 555844 - Full Discovery v-kx Job Name                                                 NaN Job Name                                                 NaN Name: 7, dtype: object', lnk:null },
  { _id:'n38', t:'t3', p:'ngpi', name:'Lightbulb Surplus', cid:'555816', freq:null, st:'churned', hd:add(60), csm:'', notes:'customer churned', job:'1 Job Name    Disabled Job Name         NaN Job Name         NaN Name: 8, dtype: object', lnk:null },
  { _id:'n39', t:'t3', p:'ngpi', name:'Rocky Mountain ATV', cid:'555824', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    RockyMountain ATV  - Full Discovery (555824) Job Name                                             NaN Job Name                                             NaN Name: 9, dtype: object', lnk:null },

  // ── NGPI — Tranche 4 ──
  { _id:'n40', t:'t4', p:'ngpi', name:'Lifetime', cid:'555099', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    lifetime 555099 - Full Discovery v-m0 Job Name                                      NaN Job Name                                      NaN Name: 0, dtype: object', lnk:null },
  { _id:'n41', t:'t4', p:'ngpi', name:'Narta WTB', cid:'555276', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    nartawtborgid212 555276 - Full Discovery v-jb Job Name                                              NaN Job Name                                              NaN Name: 1, dtype: object', lnk:null },
  { _id:'n42', t:'t4', p:'ngpi', name:'Woolworths', cid:'555779', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    woolworthsorgid725 555779 - Full Discovery v-pa Job Name                                                NaN Job Name                                                NaN Name: 2, dtype: object', lnk:null },
  { _id:'n43', t:'t4', p:'ngpi', name:'The Blue Space', cid:'555712', freq:'Daily', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    thebluespaceorgid658 555712 - Full Discovery v-ls Job Name                                                  NaN Job Name                                                  NaN Name: 3, dtype: object', lnk:null },
  { _id:'n44', t:'t4', p:'ngpi', name:'FW Webb Company', cid:'555642', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    fwwebbcompanyorgid575 555642 - Full Discovery ... Job Name                                                  NaN Job Name                                                  NaN Name: 4, dtype: object', lnk:null },
  { _id:'n45', t:'t4', p:'ngpi', name:'Musician\'s Friend', cid:'186338', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    musiciansfriend 186338 - Full Discovery v-3t Job Name                                             NaN Job Name                                             NaN Name: 5, dtype: object', lnk:null },

  // ── NGPI — Tranche 5 ──
  { _id:'n46', t:'t5', p:'ngpi', name:'Cpo2', cid:'36074', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'Complete', job:'1 Job Name    cpo2 36074 - Full Discovery v-ud Job Name                                 NaN Job Name                                 NaN Name: 0, dtype: object', lnk:null },
  { _id:'n47', t:'t5', p:'ngpi', name:'Rustoleum', cid:'555798', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'Complete', job:'1 Job Name    customerrustoleumorgid744 555798 - Full Discovery Job Name                                                  NaN Job Name                                                  NaN Name: 1, dtype: object', lnk:null },
  { _id:'n48', t:'t5', p:'ngpi', name:'Total Tools', cid:'555001', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Disabled', job:'1 Job Name    totaltools 555001 - Full Discovery v-8r Job Name                                        NaN Job Name                                        NaN Name: 2, dtype: object', lnk:null },
  { _id:'n49', t:'t5', p:'ngpi', name:'Tractor Supply (Pilot)', cid:'555062', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    tractorsupplypilot 555062 - Full Discovery v-x0 Job Name                                                NaN Job Name                                                NaN Name: 3, dtype: object', lnk:null },
  { _id:'n50', t:'t5', p:'ngpi', name:'Purina', cid:'555588', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'complete', job:'1 Job Name    purinaorgid522 555588 - Full Discovery v-ug Job Name                                            NaN Job Name                                            NaN Name: 4, dtype: object', lnk:null },
  { _id:'n51', t:'t5', p:'ngpi', name:'Basspro', cid:'555626', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'2 groups, group 1 is stil lrunning, 660k catalog', job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 5, dtype: object', lnk:null },
  { _id:'n52', t:'t5', p:'ngpi', name:'Pet Circle', cid:'555737', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'complete', job:'1 Job Name    petcircleorgid683 555737 - Full Discovery v-ns Job Name                                               NaN Job Name                                               NaN Name: 6, dtype: object', lnk:null },

  // ── NGPI — Tranche 6 ──
  { _id:'n53', t:'t6', p:'ngpi', name:'Hisenseuk', cid:'555795', freq:null, st:'production', hd:add(60), csm:'', notes:'Complete', job:'1 Job Name    hisenseukorgid741 555795 - Full Discovery v-z1 Job Name                                               NaN Job Name                                               NaN Name: 0, dtype: object', lnk:null },
  { _id:'n54', t:'t6', p:'ngpi', name:'Dafy Moto', cid:'555762', freq:null, st:'production', hd:add(60), csm:'', notes:'Complete', job:'1 Job Name    dafymotoorgid708 555762 - Full Discovery v-s8 Job Name                                              NaN Job Name                                              NaN Name: 1, dtype: object', lnk:null },
  { _id:'n55', t:'t6', p:'ngpi', name:'Woodcraft', cid:'555761', freq:null, st:'production', hd:add(60), csm:'', notes:'Complete', job:'1 Job Name    woodcraftorgid707 555761 - Full Discovery v-5b Job Name                                               NaN Job Name                                               NaN Name: 2, dtype: object', lnk:null },
  { _id:'n56', t:'t6', p:'ngpi', name:'Carbatec Australia', cid:'555771', freq:null, st:'production', hd:add(60), csm:'', notes:'Complete', job:'1 Job Name    carbatecaustraliaorgid717 555771 - Full Discov... Job Name                                                  NaN Job Name                                                  NaN Name: 3, dtype: object', lnk:null },
  { _id:'n57', t:'t6', p:'ngpi', name:'Tractor Supply (Digital)', cid:'555783', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    tractorsupplydigitalorgid729 555783 - Full Dis... Job Name                                                  NaN Job Name                                                  NaN Name: 4, dtype: object', lnk:null },
  { _id:'n58', t:'t6', p:'ngpi', name:'Medi-SPT', cid:'555774', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'Complete after bot issue resolved', job:'1 Job Name    medisptorgid720 555774 - Full Discovery v-ry Job Name                                             NaN Job Name                                             NaN Name: 5, dtype: object', lnk:null },
  { _id:'n59', t:'t6', p:'ngpi', name:'Officeworks B2C', cid:'555793', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Complete', job:'1 Job Name    officeworksb2corgid739 555793 - Full Discovery... Job Name                                                  NaN Job Name                                                  NaN Name: 6, dtype: object', lnk:null },

  // ── NGPI — Tranche 8 ──
  { _id:'n60', t:'t8', p:'ngpi', name:'Bsrstancash', cid:'555791', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    bsrstancashorgid737 555791 - Full Discovery v-lp Job Name                                                 NaN Job Name                                                 NaN Name: 0, dtype: object', lnk:null },
  { _id:'n61', t:'t8', p:'ngpi', name:'BSR Billy Guyatts', cid:'555790', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    bsrbillyguyattsorgid736 555790 - Full Discover... Job Name                                                  NaN Job Name                                                  NaN Name: 1, dtype: object', lnk:null },
  { _id:'n62', t:'t8', p:'ngpi', name:'BSR Betta Home Living', cid:'555789', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Complete, Found BOT issues', job:'1 Job Name    bsrbettahomelivingorgid735 555789 - Full Disco... Job Name                                                  NaN Job Name                                                  NaN Name: 2, dtype: object', lnk:null },
  { _id:'n63', t:'t8', p:'ngpi', name:'Ebuyer', cid:'555748', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    ebuyerorgid694 555748 - Full Discovery v-qg Job Name                                            NaN Job Name                                            NaN Name: 3, dtype: object', lnk:null },
  { _id:'n64', t:'t8', p:'ngpi', name:'Grand & Toy', cid:'555764', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    grandandtoyorgid710 555764 - Full Discovery v-bp Job Name                                                 NaN Job Name                                                 NaN Name: 4, dtype: object', lnk:null },
  { _id:'n65', t:'t8', p:'ngpi', name:'Currys UK IE', cid:'555763', freq:null, st:'production', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    currysukieorgid709 555763 - Full Discovery v-u4 Job Name                                                NaN Job Name                                                NaN Name: 5, dtype: object', lnk:null },
  { _id:'n66', t:'t8', p:'ngpi', name:'Currys UK', cid:'555760', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    currysukorgid706 555760 - Full Discovery v-zz Job Name                                              NaN Job Name                                              NaN Name: 6, dtype: object', lnk:null },

  // ── NGPI — Tranche 9 ──
  { _id:'n67', t:'t9', p:'ngpi', name:'Foodworks Australia', cid:'555691', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'waiting for customer to officially start implementation', job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 0, dtype: object', lnk:null },
  { _id:'n68', t:'t9', p:'ngpi', name:'Kirby Risk', cid:'555714', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Disabled', job:'1 Job Name    Disabled Job Name         NaN Job Name         NaN Name: 1, dtype: object', lnk:null },
  { _id:'n69', t:'t9', p:'ngpi', name:'Estradingbathrooms', cid:'555827', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    estradingbathroomsorgid773 555827 - Full Disco... Job Name                                                  NaN Job Name                                                  NaN Name: 2, dtype: object', lnk:null },
  { _id:'n70', t:'t9', p:'ngpi', name:'CSE Solutions', cid:'555832', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    csesolutionsorgid778 555832 - Full Discovery v-8y Job Name                                                  NaN Job Name                                                  NaN Name: 3, dtype: object', lnk:null },
  { _id:'n71', t:'t9', p:'ngpi', name:'Electroluxrakuten', cid:'555836', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    electroluxrakutenorgid782 555836 - Full Discov... Job Name                                                  NaN Job Name                                                  NaN Name: 4, dtype: object', lnk:null },
  { _id:'n72', t:'t9', p:'ngpi', name:'Only Natural Pet', cid:'555845', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    onlynaturalpetorgid791 555845 - Full Discovery... Job Name                                                  NaN Job Name                                                  NaN Name: 5, dtype: object', lnk:null },
  { _id:'n73', t:'t9', p:'ngpi', name:'Bulbs.com', cid:'555804', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Disabled', job:'1 Job Name    Disabled Job Name         NaN Job Name         NaN Name: 6, dtype: object', lnk:null },

  // ── NGPI — Tranche 10 ──
  { _id:'n74', t:'t10', p:'ngpi', name:'Vitaminshoppe1198340306', cid:'555815', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    vitaminshoppe1198340306orgid761 555815 - Full ... Job Name                                                  NaN Job Name                                                  NaN Name: 0, dtype: object', lnk:null },
  { _id:'n75', t:'t10', p:'ngpi', name:'Brent Industries LLC', cid:'555817', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    brentindustriesllc715571orgid763 555817 - Full... Job Name                                                  NaN Job Name                                                  NaN Name: 1, dtype: object', lnk:null },
  { _id:'n76', t:'t10', p:'ngpi', name:'Backcountrybjklffwm', cid:'555818', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Disabled', job:'1 Job Name    Disabled Job Name         NaN Job Name         NaN Name: 2, dtype: object', lnk:null },
  { _id:'n77', t:'t10', p:'ngpi', name:'Brent Industries LLC 2', cid:'555819', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Disabled', job:'1 Job Name    Disabled Job Name         NaN Job Name         NaN Name: 3, dtype: object', lnk:null },
  { _id:'n78', t:'t10', p:'ngpi', name:'Reliance Worldwide', cid:'555820', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    RelianceWorldwi de  - Full Discovery (555820) Job Name                                              NaN Job Name                                              NaN Name: 4, dtype: object', lnk:null },
  { _id:'n79', t:'t10', p:'ngpi', name:'Essendant', cid:'555821', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    Essendant  - Full Discovery9Jan 21, 2026COMPLE... Job Name                                                  NaN Job Name                                                  NaN Name: 5, dtype: object', lnk:null },
  { _id:'n80', t:'t10', p:'ngpi', name:'Katom', cid:'555822', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    Katom  - Full Discovery (555822) Job Name                                 NaN Job Name                                 NaN Name: 6, dtype: object', lnk:null },

  // ── NGPI — Tranche 11 ──
  { _id:'n81', t:'t11', p:'ngpi', name:'Realtruck', cid:'555825', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, Found BOT issues', job:'1 Job Name    Realtruck  - Full Discovery (555825) Job Name                                     NaN Job Name                                     NaN Name: 0, dtype: object', lnk:null },
  { _id:'n82', t:'t11', p:'ngpi', name:'Mattressfirm', cid:'555828', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete Checking', job:'1 Job Name    mattressfirmorgid774 555828 - Full Discovery v-og Job Name                                                  NaN Job Name                                                  NaN Name: 1, dtype: object', lnk:null },
  { _id:'n83', t:'t11', p:'ngpi', name:'Cole Haan', cid:'555829', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    Colehaan  - Full Discovery (555829) Job Name                                    NaN Job Name                                    NaN Name: 2, dtype: object', lnk:null },
  { _id:'n84', t:'t11', p:'ngpi', name:'Integrated Supply Network', cid:'555830', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Completed, After BOT issue resolved', job:'1 Job Name    IntegratedSuppl yNetwork  - Full Discovery (55... Job Name                                                  NaN Job Name                                                  NaN Name: 3, dtype: object', lnk:null },
  { _id:'n85', t:'t11', p:'ngpi', name:'Mattressfirmmatching', cid:'555831', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    Mattressfirmmat chingorgid777  - Full Disovery... Job Name                                                  NaN Job Name                                                  NaN Name: 4, dtype: object', lnk:null },
  { _id:'n86', t:'t11', p:'ngpi', name:'Wistex', cid:'555838', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    wistexorgid784 555838 - Full Discovery v-p5 Job Name                                            NaN Job Name                                            NaN Name: 5, dtype: object', lnk:null },
  { _id:'n87', t:'t11', p:'ngpi', name:'Surveillance Video', cid:'555840', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    surveillancevideoorgid786 555840 - Full Discov... Job Name                                                  NaN Job Name                                                  NaN Name: 6, dtype: object', lnk:null },
  { _id:'n88', t:'t11', p:'ngpi', name:'Rrigoods7c7tqbxkm', cid:'555841', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    rrigoods7c7tqbxkmorgid787 555841 - Full Discovery Job Name                                                  NaN Job Name                                                  NaN Name: 7, dtype: object', lnk:null },

  // ── NGPI — Tranche 12 ──
  { _id:'n89', t:'t12', p:'ngpi', name:'Backcountry', cid:'555843', freq:null, st:'onboarding', hd:add(60), csm:'', notes:'Disabled', job:'1 Job Name    Disabled Job Name         NaN Job Name         NaN Name: 0, dtype: object', lnk:null },
  { _id:'n90', t:'t12', p:'ngpi', name:'Jensonusa2', cid:'555805', freq:'Daily', st:'onboarding', hd:add(60), csm:'', notes:'Complete, No BOT issues Found', job:'1 Job Name    jensonusa2orgid751 555805 - Full Discovery v-62 Job Name                                                NaN Job Name                                                NaN Name: 1, dtype: object', lnk:null },
  { _id:'n91', t:'t12', p:'ngpi', name:'Carewell', cid:'555842', freq:'Daily', st:'onboarding', hd:add(60), csm:'', notes:'Complete, checking', job:'1 Job Name    carewell2orgid788 555842 - Full Discovery v-3k Job Name                                               NaN Job Name                                               NaN Name: 2, dtype: object', lnk:null },
  { _id:'n92', t:'t12', p:'ngpi', name:'FWW B-Zone', cid:'555700', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'Complete, checking', job:'1 Job Name    fwwbzoneorgid646 555700 - Full Discovery v-7n Job Name                                              NaN Job Name                                              NaN Name: 3, dtype: object', lnk:null },
  { _id:'n93', t:'t12', p:'ngpi', name:'Future Shop CA', cid:'4', freq:'Thrice-Weekly', st:'production', hd:add(60), csm:'', notes:'bestbuy canada', job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 4, dtype: object', lnk:null },
  { _id:'n94', t:'t12', p:'ngpi', name:'Home Depot New', cid:'3618740', freq:'Daily', st:'production', hd:add(60), csm:'', notes:'Avoid this one for now', job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 5, dtype: object', lnk:null },

  // ── NGPI — Tranche 13 ──
  { _id:'n95', t:'t13', p:'ngpi', name:'Radwell', cid:'555801', freq:null, st:'production', hd:add(60), csm:'', notes:'Do not run this yet', job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 0, dtype: object', lnk:null },
  { _id:'n96', t:'t13', p:'ngpi', name:'Zoro', cid:'555008', freq:'Weekly', st:'production', hd:add(60), csm:'', notes:'Do not run this yet', job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 1, dtype: object', lnk:null },

  // ── NGPI — Tranche Unassigned ──
  { _id:'n97', t:'tunk', p:'ngpi', name:'Costcousbundles', cid:'555854', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 0, dtype: object', lnk:null },
  { _id:'n98', t:'tunk', p:'ngpi', name:'LG Competitive', cid:'555858', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 1, dtype: object', lnk:null },
  { _id:'n99', t:'tunk', p:'ngpi', name:'The Very Group', cid:'555846', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 2, dtype: object', lnk:null },
  { _id:'n100', t:'tunk', p:'ngpi', name:'Nestle HS', cid:'555848', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 3, dtype: object', lnk:null },
  { _id:'n101', t:'tunk', p:'ngpi', name:'The Very Group', cid:'555857', freq:null, st:'production', hd:add(60), csm:'', notes:null, job:'1 Job Name    NaN Job Name    NaN Job Name    NaN Name: 4, dtype: object', lnk:null },

  // ── BPA — Active ─────────────────────────────────────────────────────────
  { _id:'ba0',  t:'bpa-t1', p:'bpa', name:'AHF',                       cid:null, freq:null, st:'production', hd:add(100), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba1',  t:'bpa-t1', p:'bpa', name:'Airxcel',                   cid:null, freq:null, st:'production', hd:add(101), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba2',  t:'bpa-t1', p:'bpa', name:'Ansell',                    cid:null, freq:null, st:'production', hd:add(102), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba3',  t:'bpa-t1', p:'bpa', name:'Arnott',                    cid:null, freq:null, st:'production', hd:add(103), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba4',  t:'bpa-t1', p:'bpa', name:'Bauerfeind',                cid:null, freq:null, st:'production', hd:add(104), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba5',  t:'bpa-t1', p:'bpa', name:'Beats by Dre UPP',          cid:null, freq:null, st:'production', hd:add(105), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba6',  t:'bpa-t1', p:'bpa', name:'Beautyrest',                cid:null, freq:null, st:'production', hd:add(106), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba7',  t:'bpa-t1', p:'bpa', name:'Beautyrest Black',          cid:null, freq:null, st:'production', hd:add(107), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba8',  t:'bpa-t1', p:'bpa', name:'Big Bike Parts',            cid:null, freq:null, st:'production', hd:add(108), csm:'Maria L.', notes:null, job:'(BPA) Bike Bike Parts - Full Discovery', lnk:'https://orchestration.wiser.com/jobs/69b8cf1d69e0c6b47f702f5e' },
  { _id:'ba9',  t:'bpa-t1', p:'bpa', name:'Bilstein',                  cid:null, freq:null, st:'production', hd:add(109), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba10', t:'bpa-t1', p:'bpa', name:'BRK',                       cid:null, freq:null, st:'production', hd:add(110), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba11', t:'bpa-t1', p:'bpa', name:'Cal Mil',                   cid:null, freq:null, st:'production', hd:add(111), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba12', t:'bpa-t1', p:'bpa', name:'Cole Haan',                 cid:null, freq:null, st:'production', hd:add(112), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba13', t:'bpa-t1', p:'bpa', name:'DanaCorp',                  cid:null, freq:null, st:'production', hd:add(113), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba14', t:'bpa-t1', p:'bpa', name:'DanaCorp UJoints',          cid:null, freq:null, st:'production', hd:add(114), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba15', t:'bpa-t1', p:'bpa', name:'Dan Post Boots',            cid:null, freq:null, st:'production', hd:add(115), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba16', t:'bpa-t1', p:'bpa', name:'Eaton Electric',            cid:null, freq:null, st:'production', hd:add(116), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba17', t:'bpa-t1', p:'bpa', name:'Eaton Vehicle Group',       cid:null, freq:null, st:'production', hd:add(117), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba18', t:'bpa-t1', p:'bpa', name:'EMC Hospitality',           cid:null, freq:null, st:'production', hd:add(118), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba19', t:'bpa-t1', p:'bpa', name:'Encompass',                 cid:null, freq:null, st:'production', hd:add(119), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba20', t:'bpa-t1', p:'bpa', name:'ENERSYS',                   cid:null, freq:null, st:'production', hd:add(120), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba21', t:'bpa-t1', p:'bpa', name:'English Riding Supply',     cid:null, freq:null, st:'production', hd:add(121), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba22', t:'bpa-t1', p:'bpa', name:'Federal Industries',        cid:null, freq:null, st:'production', hd:add(122), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba23', t:'bpa-t1', p:'bpa', name:'FedPro',                    cid:null, freq:null, st:'production', hd:add(123), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba24', t:'bpa-t1', p:'bpa', name:'Fiskars Gerber Gear',       cid:null, freq:null, st:'production', hd:add(124), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba25', t:'bpa-t1', p:'bpa', name:'Fox Head',                  cid:null, freq:null, st:'production', hd:add(125), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba26', t:'bpa-t1', p:'bpa', name:'General Motors',            cid:null, freq:null, st:'production', hd:add(126), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba27', t:'bpa-t1', p:'bpa', name:'Goodyear',                  cid:null, freq:null, st:'production', hd:add(127), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba28', t:'bpa-t1', p:'bpa', name:'Goodyear ATC',              cid:null, freq:null, st:'production', hd:add(128), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba29', t:'bpa-t1', p:'bpa', name:'Goodyear CA',               cid:null, freq:null, st:'production', hd:add(129), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba30', t:'bpa-t1', p:'bpa', name:'Grundfos',                  cid:null, freq:null, st:'production', hd:add(130), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba31', t:'bpa-t1', p:'bpa', name:'HH Brown',                  cid:null, freq:null, st:'production', hd:add(131), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba32', t:'bpa-t1', p:'bpa', name:"Hill's Pet",                cid:null, freq:null, st:'production', hd:add(132), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba33', t:'bpa-t1', p:'bpa', name:'Hoshino',                   cid:null, freq:null, st:'production', hd:add(133), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba34', t:'bpa-t1', p:'bpa', name:'Hoshizaki UPP',             cid:null, freq:null, st:'production', hd:add(134), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba35', t:'bpa-t1', p:'bpa', name:'Integrated Supply Network', cid:null, freq:null, st:'production', hd:add(135), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba36', t:'bpa-t1', p:'bpa', name:'BPA Internal',              cid:null, freq:null, st:'production', hd:add(136), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba37', t:'bpa-t1', p:'bpa', name:'Jon Renau',                 cid:null, freq:null, st:'production', hd:add(137), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba38', t:'bpa-t1', p:'bpa', name:'Jon Renau AU',              cid:null, freq:null, st:'production', hd:add(138), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba39', t:'bpa-t1', p:'bpa', name:'Justin Boots',              cid:null, freq:null, st:'production', hd:add(139), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba40', t:'bpa-t1', p:'bpa', name:'Lego',                      cid:null, freq:null, st:'production', hd:add(140), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba41', t:'bpa-t1', p:'bpa', name:'Lego RPM',                  cid:null, freq:null, st:'production', hd:add(141), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba42', t:'bpa-t1', p:'bpa', name:'LEM Products',              cid:null, freq:null, st:'production', hd:add(142), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba43', t:'bpa-t1', p:'bpa', name:'Leupold Stevens',           cid:null, freq:null, st:'production', hd:add(143), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba44', t:'bpa-t1', p:'bpa', name:'Lippert Components',        cid:null, freq:null, st:'production', hd:add(144), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba45', t:'bpa-t1', p:'bpa', name:'McLeod Racing',             cid:null, freq:null, st:'production', hd:add(145), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba46', t:'bpa-t1', p:'bpa', name:'McLeod Racing (alt)',       cid:null, freq:null, st:'production', hd:add(146), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba47', t:'bpa-t1', p:'bpa', name:'Mevotech',                  cid:null, freq:null, st:'production', hd:add(147), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba48', t:'bpa-t1', p:'bpa', name:'Mickey Thompson Tires',     cid:null, freq:null, st:'production', hd:add(148), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba49', t:'bpa-t1', p:'bpa', name:'Oculus VR',                 cid:null, freq:null, st:'production', hd:add(149), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba50', t:'bpa-t1', p:'bpa', name:'Painless Performance',      cid:null, freq:null, st:'production', hd:add(150), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba51', t:'bpa-t1', p:'bpa', name:'Pentland',                  cid:null, freq:null, st:'production', hd:add(151), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba52', t:'bpa-t1', p:'bpa', name:'Promaster',                 cid:null, freq:null, st:'production', hd:add(152), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba53', t:'bpa-t1', p:'bpa', name:'Puma',                      cid:null, freq:null, st:'production', hd:add(153), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba54', t:'bpa-t1', p:'bpa', name:'Putco',                     cid:null, freq:null, st:'production', hd:add(154), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba55', t:'bpa-t1', p:'bpa', name:'Raceline Wheels',           cid:null, freq:null, st:'production', hd:add(155), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba56', t:'bpa-t1', p:'bpa', name:'Razor',                     cid:null, freq:null, st:'production', hd:add(156), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba57', t:'bpa-t1', p:'bpa', name:'Regal Rexnord',             cid:null, freq:null, st:'production', hd:add(157), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba58', t:'bpa-t1', p:'bpa', name:'Revelyst',                  cid:null, freq:null, st:'production', hd:add(158), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba59', t:'bpa-t1', p:'bpa', name:'Rigid Industries',          cid:null, freq:null, st:'production', hd:add(159), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba60', t:'bpa-t1', p:'bpa', name:'Samsung Appliances',        cid:null, freq:null, st:'production', hd:add(160), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba61', t:'bpa-t1', p:'bpa', name:'Seirus',                    cid:null, freq:null, st:'production', hd:add(161), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba62', t:'bpa-t1', p:'bpa', name:'Serta',                     cid:null, freq:null, st:'production', hd:add(162), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba63', t:'bpa-t1', p:'bpa', name:'Serta Simmons Bedding',     cid:null, freq:null, st:'production', hd:add(163), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba64', t:'bpa-t1', p:'bpa', name:'SRAM',                      cid:null, freq:null, st:'production', hd:add(164), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba65', t:'bpa-t1', p:'bpa', name:'Standard Motor Products',   cid:null, freq:null, st:'production', hd:add(165), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba66', t:'bpa-t1', p:'bpa', name:'TireCo',                    cid:null, freq:null, st:'production', hd:add(166), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba67', t:'bpa-t1', p:'bpa', name:'TireCo RM',                 cid:null, freq:null, st:'production', hd:add(167), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba68', t:'bpa-t1', p:'bpa', name:'Trane',                     cid:null, freq:null, st:'production', hd:add(168), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba69', t:'bpa-t1', p:'bpa', name:'Traxxas',                   cid:null, freq:null, st:'production', hd:add(169), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba70', t:'bpa-t1', p:'bpa', name:'Ultimate Support',          cid:null, freq:null, st:'production', hd:add(170), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba71', t:'bpa-t1', p:'bpa', name:'Umbra',                     cid:null, freq:null, st:'production', hd:add(171), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba72', t:'bpa-t1', p:'bpa', name:'VF Imagewear US',           cid:null, freq:null, st:'production', hd:add(172), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba73', t:'bpa-t1', p:'bpa', name:'Vision Wheel',              cid:null, freq:null, st:'production', hd:add(173), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba74', t:'bpa-t1', p:'bpa', name:'Wheel Pros',                cid:null, freq:null, st:'production', hd:add(174), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba75', t:'bpa-t1', p:'bpa', name:'WWRD',                      cid:null, freq:null, st:'production', hd:add(175), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba76', t:'bpa-t1', p:'bpa', name:'Yamaha Motor',              cid:null, freq:null, st:'production', hd:add(176), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'ba77', t:'bpa-t1', p:'bpa', name:'Zoeller',                   cid:null, freq:null, st:'production', hd:add(177), csm:'Maria L.', notes:null, job:null, lnk:null },
  { _id:'bc0', t:'bpa-t2', p:'bpa', name:'Aeromotive', cid:null, freq:null, st:'churned', hd:null, csm:'Maria L.', notes:'Ignored / churned', job:null, lnk:null },
  { _id:'bc1', t:'bpa-t2', p:'bpa', name:'Jackson',    cid:null, freq:null, st:'churned', hd:null, csm:'Maria L.', notes:'Ignored / churned', job:null, lnk:null },
  { _id:'bc2', t:'bpa-t2', p:'bpa', name:'Pertronix',  cid:null, freq:null, st:'churned', hd:null, csm:'Maria L.', notes:'Ignored / churned', job:null, lnk:null },
  { _id:'bc3', t:'bpa-t2', p:'bpa', name:'Scarpa',     cid:null, freq:null, st:'churned', hd:null, csm:'Maria L.', notes:'Ignored / churned', job:null, lnk:null },

  // ── WISER MAP ─────────────────────────────────────────────────────────────
  { _id:'wm0',  t:'wmap-t1', p:'wmap', name:'LG Canada',             cid:null, freq:null, st:'production', hd:add(108), csm:'David R.', notes:'Consumer Electronics',   job:null,                                             lnk:null },
  { _id:'wm1',  t:'wmap-t1', p:'wmap', name:'100PercentMoto',        cid:null, freq:null, st:'production', hd:add(110), csm:'David R.', notes:'Apparel / Sportswear',   job:null,                                             lnk:null },
  { _id:'wm2',  t:'wmap-t1', p:'wmap', name:'ExxelOutdoors',         cid:null, freq:null, st:'production', hd:add(112), csm:'David R.', notes:'Apparel / Sportswear',   job:null,                                             lnk:null },
  { _id:'wm3',  t:'wmap-t1', p:'wmap', name:'AmericanMetalCraft',    cid:null, freq:null, st:'production', hd:add(114), csm:'David R.', notes:'Home & Kitchen',          job:'(WM) AmericanMetalCraft - Full Discovery',       lnk:'https://orchestration.wiser.com/jobs/69863a8c8f3940f5c55b488b' },
  { _id:'wm4',  t:'wmap-t1', p:'wmap', name:'Nokian',                cid:null, freq:null, st:'production', hd:add(116), csm:'David R.', notes:'Automotive',              job:null,                                             lnk:null },
  { _id:'wm5',  t:'wmap-t1', p:'wmap', name:'TYR',                   cid:null, freq:null, st:'production', hd:add(118), csm:'David R.', notes:'Apparel / Sportswear',   job:null,                                             lnk:null },
  { _id:'wm6',  t:'wmap-t1', p:'wmap', name:'Corral Boots',          cid:null, freq:null, st:'production', hd:add(120), csm:'David R.', notes:'Apparel / Sportswear',   job:'(WM) Corral Boots - Full Discovery',              lnk:'https://orchestration.wiser.com/jobs/69ab5fd1de871104d1fd2dac' },
  { _id:'wm7',  t:'wmap-t1', p:'wmap', name:'Round 2 Corp',          cid:null, freq:null, st:'production', hd:add(122), csm:'David R.', notes:'Automotive / Industrial', job:null,                                             lnk:null },
  { _id:'wm8',  t:'wmap-t1', p:'wmap', name:'STI',                   cid:null, freq:null, st:'production', hd:add(124), csm:'David R.', notes:'Industrial / B2B',       job:'(WM) Specified Technologies - Full Discovery',    lnk:'https://orchestration.wiser.com/jobs/6991431176f68e44eb2e08a2' },
  { _id:'wm9',  t:'wmap-t1', p:'wmap', name:'New Balance',           cid:null, freq:null, st:'production', hd:add(126), csm:'David R.', notes:'Apparel / Sportswear',   job:'(WM) New Balance - Full Discovery',               lnk:'https://orchestration.wiser.com/jobs/6993444b76f68e44eb2faceb' },
  { _id:'wm10', t:'wmap-t1', p:'wmap', name:'Nutramax',              cid:null, freq:null, st:'production', hd:add(128), csm:'David R.', notes:'Pet Supplies',            job:null,                                             lnk:null },
  { _id:'wm11', t:'wmap-t1', p:'wmap', name:'Hypard',                cid:null, freq:null, st:'production', hd:add(130), csm:'David R.', notes:'Apparel / Sportswear',   job:'(WM) Hypard - Full Discovery',                   lnk:'https://orchestration.wiser.com/jobs/69863e3ce848ba27197c31a2' },
  { _id:'wm12', t:'wmap-t1', p:'wmap', name:'EnhancedLaserProducts', cid:null, freq:null, st:'production', hd:add(132), csm:'David R.', notes:'Industrial / B2B',       job:'(WM) EnhancedLaserProducts - Full Discovery',    lnk:'https://orchestration.wiser.com/jobs/698640018f3940f5c55b495a' },
  { _id:'wm13', t:'wmap-t1', p:'wmap', name:'Prym MAP',              cid:null, freq:null, st:'production', hd:add(134), csm:'David R.', notes:'Pet Supplies',            job:'(WM) Prym - Full Discovery',                     lnk:'https://orchestration.wiser.com/jobs/699157dd76f68e44eb2e1263' },

  // ── NUMAP ─────────────────────────────────────────────────────────────────
  { _id:'nm1-0',  t:'nm-t1', p:'numap', name:'Rockford Fosgate 5730',          cid:null, freq:'Yearly',             st:'production', hd:add(85),  csm:'Priya N.', notes:'Consumer Electronics > Audio > Automotive', job:null,                                                     lnk:null },
  { _id:'nm1-1',  t:'nm-t1', p:'numap', name:'Canon 672 Printer',              cid:null, freq:'Weekly or Monthly',  st:'production', hd:add(87),  csm:'Priya N.', notes:'Consumer Electronics',                     job:'(CA) Canon672_Printer - Full Discovery',           lnk:'https://orchestration.wiser.com/jobs/69987342871be482a7af11be' },
  { _id:'nm1-2',  t:'nm-t1', p:'numap', name:'Motorola Solutions Canada',      cid:null, freq:'Monthly or Quarterly',st:'production',hd:add(89),  csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-3',  t:'nm-t1', p:'numap', name:'Lexmark 5404',                   cid:null, freq:'Monthly',            st:'production', hd:add(91),  csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-4',  t:'nm-t1', p:'numap', name:'Timex MAP',                      cid:null, freq:'Half Yearly',        st:'production', hd:add(93),  csm:'Priya N.', notes:'Consumer Electronics',                     job:'(CA) Timex - Full Discovery',                      lnk:'https://orchestration.wiser.com/jobs/699875bf60f6b6b384ce2fbc' },
  { _id:'nm1-5',  t:'nm-t1', p:'numap', name:'QSC 202',                        cid:null, freq:'Yearly',             st:'production', hd:add(95),  csm:'Priya N.', notes:'Consumer Electronics > Audio > Pro Systems',job:'(CA) QSC - Full Discovery',                        lnk:'https://orchestration.wiser.com/jobs/69861c578f3940f5c55b33e4' },
  { _id:'nm1-6',  t:'nm-t1', p:'numap', name:'Google Inc Canada',              cid:null, freq:'Yearly',             st:'production', hd:add(97),  csm:'Priya N.', notes:'Consumer Electronics',                     job:'(CA) Google Canada - Full Discovery',              lnk:'https://orchestration.wiser.com/jobs/698e8a0de848ba2719805d24' },
  { _id:'nm1-7',  t:'nm-t1', p:'numap', name:'Sharp B2B 4916',                 cid:null, freq:'Quarterly',          st:'production', hd:add(99),  csm:'Priya N.', notes:'Consumer Electronics',                     job:'(CA) SharpB2B4916 - Full Discovery',               lnk:'https://orchestration.wiser.com/jobs/699889333bc48005346786a2' },
  { _id:'nm1-8',  t:'nm-t1', p:'numap', name:'Philips Canada',                 cid:null, freq:'Monthly',            st:'production', hd:add(101), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-9',  t:'nm-t1', p:'numap', name:'Google Inc 5573',                cid:null, freq:'Yearly',             st:'production', hd:add(103), csm:'Priya N.', notes:'Consumer Electronics',                     job:'(CA) GoogleInc5573 - Full Discovery',              lnk:'https://orchestration.wiser.com/jobs/698630511f4ec7bc059889bd' },
  { _id:'nm1-10', t:'nm-t1', p:'numap', name:'Logitech',                       cid:null, freq:'Monthly',            st:'production', hd:add(105), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-11', t:'nm-t1', p:'numap', name:'Sony Interactive Entertainment', cid:null, freq:'Monthly',            st:'production', hd:add(107), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-12', t:'nm-t1', p:'numap', name:'Philips 2025 MAP Program',       cid:null, freq:'Weekly',             st:'production', hd:add(109), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-13', t:'nm-t1', p:'numap', name:'LG Home Appliances',             cid:null, freq:'Weekly',             st:'production', hd:add(111), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-14', t:'nm-t1', p:'numap', name:'Philips Domestic Appliances CA', cid:null, freq:'Half yearly',        st:'production', hd:add(113), csm:'Priya N.', notes:'Consumer Electronics',                     job:'(CA) Philips Domestic Appliances CA - Full Discovery',lnk:'https://orchestration.wiser.com/jobs/69988f615b101c5eafc46296' },
  { _id:'nm1-15', t:'nm-t1', p:'numap', name:'LG Electronics UPP',             cid:null, freq:'Weekly',             st:'production', hd:add(115), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-16', t:'nm-t1', p:'numap', name:'LG Electronics',                 cid:null, freq:'Weekly',             st:'production', hd:add(117), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-17', t:'nm-t1', p:'numap', name:'Canon 672',                      cid:null, freq:'Weekly or Monthly',  st:'production', hd:add(119), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-18', t:'nm-t1', p:'numap', name:'Sony IPSA',                      cid:null, freq:'Monthly or Quarterly',st:'production',hd:add(121), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm1-19', t:'nm-t1', p:'numap', name:'Sony Electronics',               cid:null, freq:'Weekly',             st:'production', hd:add(123), csm:'Priya N.', notes:'Consumer Electronics',                     job:null,                                                     lnk:null },
  { _id:'nm2-0', t:'nm-t2', p:'numap', name:'Goodman Canada',             cid:null, freq:'Quarterly',            st:'production', hd:add(105), csm:'Priya N.', notes:'Heating and Cooling / HVAC',             job:null, lnk:null },
  { _id:'nm2-1', t:'nm-t2', p:'numap', name:'Goodman Turk Bundle MAP',    cid:null, freq:'Quarterly',            st:'production', hd:add(107), csm:'Priya N.', notes:'Heating and Cooling / HVAC',             job:null, lnk:null },
  { _id:'nm2-2', t:'nm-t2', p:'numap', name:'Philips Domestic Appl. US',  cid:null, freq:'Half yearly',         st:'production', hd:add(109), csm:'Priya N.', notes:'Domestic Appliances',                    job:null, lnk:null },
  { _id:'nm2-3', t:'nm-t2', p:'numap', name:"D'Addario 2421",             cid:null, freq:'Monthly',             st:'production', hd:add(111), csm:'Priya N.', notes:'Musical Instruments & Pro Audio',        job:null, lnk:null },
  { _id:'nm2-4', t:'nm-t2', p:'numap', name:'Motorola',                   cid:null, freq:'Monthly or Quarterly',st:'production', hd:add(113), csm:'Priya N.', notes:'Professional Communications Equipment',  job:null, lnk:null },
  { _id:'nm2-5', t:'nm-t2', p:'numap', name:'Philips Lighting',           cid:null, freq:'Discontinue',         st:'production', hd:add(115), csm:'Priya N.', notes:'Home Improvement > Lighting',            job:null, lnk:null },
  { _id:'nm2-6', t:'nm-t2', p:'numap', name:'Goodman 5223',               cid:null, freq:'Quarterly',           st:'production', hd:add(117), csm:'Priya N.', notes:'Heating and Cooling / HVAC',             job:null, lnk:null },
  { _id:'nm3-0', t:'nm-t3', p:'numap', name:'Livon 578',          cid:null, freq:'Yearly',              st:'production', hd:add(125), csm:'Tom W.', notes:'Health & Beauty > Supplements',  job:null,                                       lnk:null },
  { _id:'nm3-1', t:'nm-t3', p:'numap', name:'Citizen International',cid:null,freq:'Quarterly',           st:'production', hd:add(127), csm:'Tom W.', notes:'Accessories > Watches',          job:null,                                       lnk:null },
  { _id:'nm3-2', t:'nm-t3', p:'numap', name:'Steve Madden 5376',   cid:null, freq:'Monthly or Quarterly',st:'production', hd:add(129), csm:'Tom W.', notes:'Apparel',                        job:null,                                       lnk:null },
  { _id:'nm3-3', t:'nm-t3', p:'numap', name:'Converse Canada',     cid:null, freq:'Monthly',             st:'production', hd:add(131), csm:'Tom W.', notes:'Apparel',                        job:null,                                       lnk:null },
  { _id:'nm3-4', t:'nm-t3', p:'numap', name:'Citizen 4927',        cid:null, freq:'Yearly',              st:'production', hd:add(133), csm:'Tom W.', notes:'Accessories > Watches',          job:null,                                       lnk:null },
  { _id:'nm3-5', t:'nm-t3', p:'numap', name:'Colgate 2015',        cid:null, freq:'Yearly',              st:'production', hd:add(135), csm:'Tom W.', notes:'Health & Beauty > Oral Care',    job:'(CA) Colgate 2026 - Full Discovery',       lnk:'https://orchestration.wiser.com/jobs/69ab633ed5048e1f45819d5d' },
  { _id:'nm3-6', t:'nm-t3', p:'numap', name:'Bayer MAP',           cid:null, freq:'Monthly or Quarterly',st:'production', hd:add(137), csm:'Tom W.', notes:'Health & Beauty > Supplements',  job:null,                                       lnk:null },
  { _id:'nm3-7', t:'nm-t3', p:'numap', name:'Kawasaki Demo 5721',  cid:null, freq:'Monthly',             st:'production', hd:add(139), csm:'Tom W.', notes:'Automotive',                     job:null,                                       lnk:null },
  { _id:'nm3-8', t:'nm-t3', p:'numap', name:'Converse',            cid:null, freq:'Half yearly',         st:'production', hd:add(141), csm:'Tom W.', notes:'Apparel',                        job:null,                                       lnk:null },

];
